"""empty message

Revision ID: 02303ac95af5
Revises: 50d99553701e
Create Date: 2022-02-05 16:29:43.533717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02303ac95af5'
down_revision = '50d99553701e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nfts_nft_id_key', 'nfts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('nfts_nft_id_key', 'nfts', ['nft_id'])
    # ### end Alembic commands ###
