"""empty message

Revision ID: 0d1b9adb5eb7
Revises: b4b449c6f1d3
Create Date: 2022-01-28 00:40:05.151557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1b9adb5eb7'
down_revision = 'b4b449c6f1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collections_contract_account_key', 'collections', type_='unique')
    op.drop_constraint('collections_description_key', 'collections', type_='unique')
    op.drop_constraint('collections_name_key', 'collections', type_='unique')
    op.drop_constraint('collections_owner_account_key', 'collections', type_='unique')
    op.drop_constraint('collections_url_key', 'collections', type_='unique')
    op.drop_constraint('nfts_contract_id_key', 'nfts', type_='unique')
    op.drop_constraint('nfts_image_url_key', 'nfts', type_='unique')
    op.drop_constraint('nfts_name_key', 'nfts', type_='unique')
    op.drop_constraint('nfts_nft_id_key', 'nfts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('nfts_nft_id_key', 'nfts', ['nft_id'])
    op.create_unique_constraint('nfts_name_key', 'nfts', ['name'])
    op.create_unique_constraint('nfts_image_url_key', 'nfts', ['image_url'])
    op.create_unique_constraint('nfts_contract_id_key', 'nfts', ['contract_id'])
    op.create_unique_constraint('collections_url_key', 'collections', ['url'])
    op.create_unique_constraint('collections_owner_account_key', 'collections', ['owner_account'])
    op.create_unique_constraint('collections_name_key', 'collections', ['name'])
    op.create_unique_constraint('collections_description_key', 'collections', ['description'])
    op.create_unique_constraint('collections_contract_account_key', 'collections', ['contract_account'])
    # ### end Alembic commands ###
