"""empty message

Revision ID: 50d99553701e
Revises: 845677b723d2
Create Date: 2022-02-04 01:00:14.295010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d99553701e'
down_revision = '845677b723d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('collections', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('collections', 'attributes',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('collections', 'url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('collections', 'owner_account',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('collections', 'contract_account',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'contract_account',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('collections', 'owner_account',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('collections', 'url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('collections', 'attributes',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('collections', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('collections', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
