"""empty message

Revision ID: 767180d079cd
Revises: b61ee8e4f545
Create Date: 2022-01-28 20:13:16.057863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767180d079cd'
down_revision = 'b61ee8e4f545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nfts', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('nfts', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('nfts', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('nfts', 'nft_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('nfts', 'contract_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('nfts', 'image_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nfts', 'image_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('nfts', 'contract_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('nfts', 'nft_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('nfts', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('nfts', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('nfts', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
