"""empty message

Revision ID: 845677b723d2
Revises: 767180d079cd
Create Date: 2022-02-02 00:08:54.694342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845677b723d2'
down_revision = '767180d079cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nfts', ['nft_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nfts', type_='unique')
    # ### end Alembic commands ###
