"""empty message

Revision ID: b61ee8e4f545
Revises: 0d1b9adb5eb7
Create Date: 2022-01-28 01:50:18.727949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61ee8e4f545'
down_revision = '0d1b9adb5eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('mainnet', sa.Boolean(), nullable=True))
    op.drop_column('nfts', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfts', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('collections', 'mainnet')
    # ### end Alembic commands ###
